export { default as LoginPage } from "./auth/LoginPage";
export { default as SignupPage } from "./auth/SignupPage";
export { default as CustomersPage } from "./customers/CustomersPage";
export { default as OverviewPage } from "./dashboard/OverviewPage";
export { default as MenuPage } from "./menu/MenuPage";
export { default as OrdersPage } from "./orders/OrdersPage";
export { default as SettingsPage } from "./settings/SettingsPage";
export { default as NotFoundPage } from "./not-found-page";
export { default as User } from "./user/User";
